### ISSUE TITLE
AttributeError: 'FunctionCall' object has no attribute 'expressions'

### ISSUE THREAD

**Issue by huhuang03** [NightNord/ljd#20]
The call stack:

```
  File "main.py"
    ljd.ast.unwarper.unwarp(ast)
  File "/Users/yi/Developer/source/ljd/ljd/ast/unwarper.py", line 35, in unwarp
    _run_step(_unwarp_expressions, node)
  File "/Users/yi/Developer/source/ljd/ljd/ast/unwarper.py", line 43, in _run_step
    statements.contents = step(statements.contents, **kargs)
  File "/Users/yi/Developer/source/ljd/ljd/ast/unwarper.py", line 103, in _unwarp_expressions
    expressions = _find_expressions(start, body, end)
  File "/Users/yi/Developer/source/ljd/ljd/ast/unwarper.py", line 305, in _find_expressions
    slot, slot_type = _get_simple_local_assignment_slot(start, body, end)
  File "/Users/yi/Developer/source/ljd/ljd/ast/unwarper.py", line 463, in _get_simple_local_assignment_slot
    true, _false, body = _get_terminators(body)
  File "/Users/yi/Developer/source/ljd/ljd/ast/unwarper.py", line 861, in _get_terminators
    src = prev.contents[0].expressions.contents[0]
AttributeError: 'FunctionCall' object has no attribute 'expressions'
```

And the code:
```
print(type(prev.contents[0]))
src = prev.contents[0].expressions.contents[0]
```

mostly the type is `<class 'ljd.ast.nodes.Assignment'>`, which is right.
But when the type is `<class 'ljd.ast.nodes.FunctionCall'>`, the error occuse

**Comment by jjdredd** [comment]
This repo/program is not supported

**Comment by huhuang03** [comment]
Thank you for your reply.
Could you tell me the not supported reason is luajit version 
or some todos in the ReamdMe. [](https://github.com/NightNord/ljd#todo)

This program luajit version is 2.0.3 and lua version is 5.1.

**Comment by jjdredd** [comment]
ljd isn't complete. It can only work with certain simpler cases. It requires major fixes and additions.

**Comment by huhuang03** [comment]
Got it! Thank you!

**Comment by pkujhd** [comment]
@huhuang03 , this error because the luajit script has not debug info, so some local identifiers are not marked，they are merged in function _eliminate_simple_cases. so have many execptions. it is hard to fix.

**Comment by huhuang03** [comment]
@pkujhd Ok, luajit -bl can give some thing, can this help?
